export const state = {
  _isBot: false,
  _botScore: 0,
  _verified: false,
  _challengePassed: false,
  _forceFailFirst: false,
  _hpFilled: false,
  _powSolved: false,
  _powNonce: null,
  _powChallenge: null,
  _powResult: null,
  _powDone: false,
  _vToken: null,
  _vTokenExp: 0,
  _vLastActivity: Date.now(),
  _vTokenRefreshInterval: null,
  _vIpPenalty: 0,
  _vIpFlags: [],
};
